# Build stage
FROM node:18-alpine as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Production stage
FROM nginx:stable-alpine as production-stage

# Install envsubst (it comes with gettext)
RUN apk add --no-cache gettext

# Copy built files
COPY --from=build-stage /app/dist /usr/share/nginx/html

# Copy template and entrypoint
COPY nginx.frontend.conf.template /etc/nginx/templates/default.conf.template
COPY frontend_entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

# Start using entrypoint
CMD ["/usr/local/bin/entrypoint.sh"]
