<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\SiteSetting;

class SyncSettingsSeeder extends Seeder
{
    public function run()
    {
        $settings = [
            ['key' => 'admin_company_name', 'group' => 'admin_identity', 'value' => 'TiT'],
            ['key' => 'remove_admin_logo', 'group' => 'general', 'value' => '0'],
            ['key' => 'hero_title', 'group' => 'hero', 'value' => 'Experience the Future of'],
            ['key' => 'hero_title_gradient', 'group' => 'hero', 'value' => 'Quality Online Learning'],
            ['key' => 'hero_description', 'group' => 'hero', 'value' => 'Top-notch online tutoring from qualified tutors at the comfort of your home.                                        Join thousands of students achieving academic excellence with personalized learning.'],
            ['key' => 'stats_years', 'group' => 'sections', 'value' => '10'],
            ['key' => 'stats_students', 'group' => 'sections', 'value' => '10000'],
            ['key' => 'stats_tutors', 'group' => 'sections', 'value' => '200'],
            ['key' => 'classes_title', 'group' => 'classes', 'value' => 'Explore & Enrolls'],
            ['key' => 'classes_subtitle', 'group' => 'classes', 'value' => 'Online Tuition for all subjects - Grade 1 to Advanced Level. Group or one-on-one? We got you!s'],
            ['key' => 'classes_direct_description', 'group' => 'classes', 'value' => 'Comprehensive face-to-face learning experience with expert tutors in a physical classroom setting.'],
            ['key' => 'classes_direct_duration', 'group' => 'classes', 'value' => 'Flexible schedules'],
            ['key' => 'classes_direct_price', 'group' => 'classes', 'value' => 'Affordable rates'],
            ['key' => 'classes_direct_format', 'group' => 'classes', 'value' => 'Small Groups'],
            ['key' => 'classes_direct_features', 'group' => 'classes', 'value' => 'Small group sessions
Direct teacher interaction
Physical learning materials
In-person assessments
Focus and discipline'],
            ['key' => 'classes_direct_subjects', 'group' => 'classes', 'value' => 'Mathematics, Science, English, Sinhala, Tamils History, Geographys Commerce, ICT, Art'],
            ['key' => 'classes_online_description', 'group' => 'classes', 'value' => 'Convenient live interactive sessions accessible from anywhere with high-quality digital resources.'],
            ['key' => 'classes_online_duration', 'group' => 'classes', 'value' => 'Flexible schedules'],
            ['key' => 'classes_online_price', 'group' => 'classes', 'value' => 'Competitive pricing'],
            ['key' => 'classes_online_format', 'group' => 'classes', 'value' => 'Group & One-on-One'],
            ['key' => 'classes_online_features', 'group' => 'classes', 'value' => 'Interactive live classes
Recorded lesson access
Digital study materials
Online quizzes/exams
Flexible learning from home'],
            ['key' => 'classes_online_subjects', 'group' => 'classes', 'value' => 'Mathematics, Physics, Chemistry, Biology, English, Business Studies, Economics, Accounting, ICT, Computer Science'],
            ['key' => 'footer_logo_text', 'group' => 'footer', 'value' => 'TiT'],
            ['key' => 'footer_tagline', 'group' => 'footer', 'value' => 'Your Education..! Our Priority..!'],
            ['key' => 'footer_description', 'group' => 'footer', 'value' => 'Sri Lanka\'s trusted leader in online tuition. We ensure student success through personalized learning and comprehensive support.'],
            ['key' => 'footer_legal_title', 'group' => 'footer', 'value' => 'Legal'],
            ['key' => 'footer_privacy_label', 'group' => 'footer', 'value' => 'Privacy Policy'],
            ['key' => 'footer_terms_label', 'group' => 'footer', 'value' => 'Terms & Conditions'],
            ['key' => 'footer_refund_label', 'group' => 'footer', 'value' => 'Refund Policy'],
            ['key' => 'footer_quick_links_title', 'group' => 'footer', 'value' => 'Quick Links'],
            ['key' => 'footer_gallery_label', 'group' => 'footer', 'value' => 'Gallery'],
            ['key' => 'footer_tutor_label', 'group' => 'footer', 'value' => 'Apply as a Tutor'],
            ['key' => 'footer_student_label', 'group' => 'footer', 'value' => 'Register as a student'],
            ['key' => 'footer_contact_title', 'group' => 'footer', 'value' => 'Contact'],
            ['key' => 'footer_email', 'group' => 'footer', 'value' => 'info@edulearns.lk'],
            ['key' => 'footer_phone', 'group' => 'footer', 'value' => '+94 767206279'],
            ['key' => 'footer_copyright', 'group' => 'footer', 'value' => '© 2025 TiT. All rights reserved by TIT Online Education (PVT) Ltd.'],
            ['key' => 'social_facebook', 'group' => 'social', 'value' => 'https://web.facebook.com/?_rdc=1&_rdr#'],
            ['key' => 'social_instagram', 'group' => 'social', 'value' => '#'],
            ['key' => 'social_youtube', 'group' => 'social', 'value' => '#'],
            ['key' => 'social_twitter', 'group' => 'social', 'value' => '#'],
            ['key' => 'social_linkedin', 'group' => 'social', 'value' => '#'],
            ['key' => 'contact_hero_badge', 'group' => 'contact', 'value' => 'Contact Us'],
            ['key' => 'contact_hero_title', 'group' => 'contact', 'value' => 'Let\'s Start a Conversation'],
            ['key' => 'contact_hero_desc', 'group' => 'contact', 'value' => 'Have questions about our courses? Want to enroll? We\'re here to help. Reach out to us through any channel below.'],
            ['key' => 'contact_stat1_label', 'group' => 'contact', 'value' => '24/7 Support'],
            ['key' => 'contact_stat1_desc', 'group' => 'contact', 'value' => 'Always available'],
            ['key' => 'contact_stat2_desc', 'group' => 'contact', 'value' => 'Trust us'],
            ['key' => 'stats_success_rate', 'group' => 'sections', 'value' => '98%'],
            ['key' => 'contact_stat3_desc', 'group' => 'contact', 'value' => 'Satisfaction Rate'],
            ['key' => 'contact_form_title', 'group' => 'contact', 'value' => 'Send Us a Message'],
            ['key' => 'contact_form_desc', 'group' => 'contact', 'value' => 'Fill out the form below and we\'ll respond within 24 hours.'],
            ['key' => 'contact_label_name', 'group' => 'contact', 'value' => 'Full Name'],
            ['key' => 'contact_label_email', 'group' => 'contact', 'value' => 'Email'],
            ['key' => 'contact_label_phone', 'group' => 'contact', 'value' => 'Phone'],
            ['key' => 'contact_label_subject', 'group' => 'contact', 'value' => 'Subject'],
            ['key' => 'contact_label_message', 'group' => 'contact', 'value' => 'Message'],
            ['key' => 'contact_form_button', 'group' => 'contact', 'value' => 'Send Message'],
            ['key' => 'contact_location', 'group' => 'contact', 'value' => 'Alaveddy, Sri Lanka'],
            ['key' => 'contact_hours_title', 'group' => 'contact', 'value' => 'Support Hours'],
            ['key' => 'contact_hours_label_weekdays', 'group' => 'contact', 'value' => 'Monday - Friday'],
            ['key' => 'contact_hours_weekdays', 'group' => 'contact', 'value' => '9:00 AM - 6:00 PM'],
            ['key' => 'contact_hours_label_saturday', 'group' => 'contact', 'value' => 'Saturday'],
            ['key' => 'contact_hours_saturday', 'group' => 'contact', 'value' => '9:00 AM - 2:00 PM'],
            ['key' => 'contact_hours_label_sunday', 'group' => 'contact', 'value' => 'Sunday'],
            ['key' => 'contact_hours_sunday', 'group' => 'contact', 'value' => 'Closed'],
            ['key' => 'contact_social_title', 'group' => 'contact', 'value' => 'Connect With Us'],
            ['key' => 'social_whatsapp', 'group' => 'social', 'value' => '#'],
            ['key' => 'social_tiktok', 'group' => 'social', 'value' => '#'],
            ['key' => 'contact_urgent_title', 'group' => 'contact', 'value' => 'Need Urgent Help?'],
            ['key' => 'contact_urgent_desc', 'group' => 'contact', 'value' => 'Call our support line directly for immediate assistance.'],
            ['key' => 'contact_urgent_button', 'group' => 'contact', 'value' => 'Call Now'],
            ['key' => 'contact_map_title', 'group' => 'contact', 'value' => 'Our Location'],
            ['key' => 'contact_map_desc', 'group' => 'contact', 'value' => 'Find us on the map or visit our office directly.'],
            ['key' => 'contact_map_pin_name', 'group' => 'contact', 'value' => 'TiT Education'],
            ['key' => 'contact_map_embed_link', 'group' => 'contact', 'value' => '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3931.964709012591!2d80.00635637583142!3d9.76905357696446!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3affab53cf231405%3A0x2f4a747312823206!2stit%20alaveddy!5e0!3m2!1sen!2slk!4v1773728665734!5m2!1sen!2slk" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>'],
            ['key' => 'about_title', 'group' => 'sections', 'value' => 'About TiT Online Education'],
            ['key' => 'about_subtitle', 'group' => 'sections', 'value' => 'Sri Lanka\'s Premier Choice for Online Tuition 🎓'],
            ['key' => 'about_description', 'group' => 'sections', 'value' => 'Sri Lanka\'s trusted leader in online tuition. We ensure student success through personalized learning and comprehensive parental support. Invest in your child\'s successful learning journey with TiT Online Education.'],
            ['key' => 'about_mission_title', 'group' => 'sections', 'value' => 'Our Mission'],
            ['key' => 'about_mission_text', 'group' => 'sections', 'value' => 'To democratize quality education by making world-class online tuition accessible to every student in Sri Lanka. We believe that every child deserves the opportunity to excel academically, regardless of their location or background. Through innovative teaching methods, personalized learning paths, and dedicated support, we empower students to achieve their full potential and succeed in their academic journey.'],
            ['key' => 'about_mission_image', 'group' => 'sections', 'value' => 'http://127.0.0.1:8000/uploads/settings/1773424092_69b44ddc82512.jpeg'],
            ['key' => 'about_cta_title', 'group' => 'sections', 'value' => 'Ready to Start Your Learning Journey?'],
            ['key' => 'about_cta_desc', 'group' => 'sections', 'value' => 'Join thousands of students who are already achieving academic excellence with TiT Online Education.'],
            ['key' => 'about_cta_btn1', 'group' => 'sections', 'value' => 'Register Now'],
            ['key' => 'about_cta_btn2', 'group' => 'sections', 'value' => 'Contact Us'],
            ['key' => 'about_teachers', 'group' => 'sections', 'value' => '[{"name":"G. Hajananan","subject":"Mathematics","qualification":"Ph.D. in Mathematics","experience":"15+ years","image":"http://127.0.0.1:8000/uploads/settings/1773744391_69b931075fc19.jpeg"},{"name":"S.Nishankan","subject":"English","qualification":"Ph.D. in English","experience":"15+ years","image":"http://127.0.0.1:8000/uploads/settings/1773744776_69b93288327dc.jpeg"}]'],
            ['key' => 'about_features_title', 'group' => 'sections', 'value' => 'What Makes Us Different'],
            ['key' => 'about_features_subtitle', 'group' => 'sections', 'value' => 'Quality Assured Online Learning with Proven Results'],
            ['key' => 'about_features', 'group' => 'sections', 'value' => '[{"icon":"FiBookOpen","title":"Top-notch Online Classes","description":"Interactive live sessions...","image":"https://images.unsplash.com/photo-1522202176988-66273c2fd55f"}]'],
            ['key' => 'about_journey', 'group' => 'sections', 'value' => '[{"year":"2024","achievement":"10,000+ Students","description":"Reached a milestone..."}]'],
            ['key' => 'about_values_title', 'group' => 'sections', 'value' => 'Our Core Values'],
            ['key' => 'about_values_subtitle', 'group' => 'sections', 'value' => 'The Principles That Guide Everything We Do'],
            ['key' => 'about_values', 'group' => 'sections', 'value' => '[{"icon":"FiHeart","title":"Student-Centered","description":"Every decision we make..."}]'],
            ['key' => 'about_gallery', 'group' => 'sections', 'value' => '[{"category":"Teacher Training","title":"goof","image":"http://127.0.0.1:8000/uploads/settings/1773466189_69b4f24d75655.jpeg"},{"category":"venthan","title":"goof","image":"http://127.0.0.1:8000/uploads/settings/1773743989_69b92f759ba6a.jpeg"}]'],
            ['key' => 'about_gallery_categories', 'group' => 'sections', 'value' => 'Online Class Sessions, Student Success Stories, Teacher Training, Award Ceremony,venthan'],
            ['key' => 'register_title', 'group' => 'register', 'value' => 'Student Details'],
            ['key' => 'register_subtitle', 'group' => 'register', 'value' => 'Please fill in all the required informations'],
            ['key' => 'register_fullname_label', 'group' => 'register', 'value' => 'Full Name'],
            ['key' => 'register_phone_label', 'group' => 'register', 'value' => 'Phone Number (WhatsApp)'],
            ['key' => 'register_dob_label', 'group' => 'register', 'value' => 'Date of Birth'],
            ['key' => 'register_gender_label', 'group' => 'register', 'value' => 'Gender'],
            ['key' => 'register_school_label', 'group' => 'register', 'value' => 'School Name'],
            ['key' => 'register_medium_label', 'group' => 'register', 'value' => 'Medium of Learning'],
            ['key' => 'register_experience_label', 'group' => 'register', 'value' => 'Do you have online class experience?'],
            ['key' => 'register_device_label', 'group' => 'register', 'value' => 'Device Used for Online Classes'],
            ['key' => 'register_grade_label', 'group' => 'register', 'value' => 'Current Grade (2026)'],
            ['key' => 'register_stream_label', 'group' => 'register', 'value' => 'Stream'],
            ['key' => 'register_next_btn', 'group' => 'register', 'value' => 'Next: Payment'],
            ['key' => 'topbar_show_fb', 'group' => 'topbar', 'value' => 'yes'],
            ['key' => 'topbar_show_insta', 'group' => 'topbar', 'value' => 'yes'],
            ['key' => 'topbar_show_youtube', 'group' => 'topbar', 'value' => 'yes'],
            ['key' => 'topbar_show_email', 'group' => 'topbar', 'value' => 'yes'],
            ['key' => 'topbar_show_lang', 'group' => 'topbar', 'value' => 'yes'],
            ['key' => 'nav_home', 'group' => 'navigation', 'value' => 'Home'],
            ['key' => 'nav_about', 'group' => 'navigation', 'value' => 'About Us'],
            ['key' => 'nav_classes', 'group' => 'navigation', 'value' => 'Our Classes'],
            ['key' => 'nav_learning_suite', 'group' => 'navigation', 'value' => 'Learning Suite'],
            ['key' => 'nav_contact', 'group' => 'navigation', 'value' => 'Contact Us'],
            ['key' => 'admin_logo', 'group' => 'admin_identity', 'value' => 'uploads/settings/admin_logo_1773684551.jpeg'],
            ['key' => 'logo_url', 'group' => 'admin_identity', 'value' => 'http://127.0.0.1:8000/uploads/settings/admin_logo_1773684551.jpeg'],
            ['key' => 'love_us_title', 'group' => 'sections', 'value' => 'Students & Parents Love Us'],
            ['key' => 'love_us_subtitle', 'group' => 'sections', 'value' => 'Join thousands of satisfied students and parents who trust TiT Online Education'],
            ['key' => 'love_us_stat1_number', 'group' => 'sections', 'value' => '10,000+'],
            ['key' => 'love_us_stat1_label', 'group' => 'sections', 'value' => 'Happy Students'],
            ['key' => 'love_us_stat2_number', 'group' => 'sections', 'value' => '98%'],
            ['key' => 'love_us_stat2_label', 'group' => 'sections', 'value' => 'Success Rate'],
            ['key' => 'love_us_stat3_number', 'group' => 'sections', 'value' => '4.9/5'],
            ['key' => 'love_us_stat3_label', 'group' => 'sections', 'value' => 'Review Rating'],
            ['key' => 'love_us_stat4_number', 'group' => 'sections', 'value' => '95%'],
            ['key' => 'love_us_stat4_label', 'group' => 'sections', 'value' => 'Pass Guarantee'],
            ['key' => 'love_us_testimonials', 'group' => 'sections', 'value' => '[{"name":"nisankan","role":"parent","student":"Grade 10 Student","rating":"3","comment":"\"The personalized attention and quality teaching have improved my daughter\'s grades significantly. Highly recommended!\"","image":"http://127.0.0.1:8000/uploads/settings/1773751426_69b94c82ba541.jpeg"},{"name":"SuperAdmin Test","role":"","student":"","rating":"5","comment":"Testing with super_admin access","image":""}]'],
            ['key' => 'why_title', 'group' => 'sections', 'value' => 'Why EduLearn?ssss'],
            ['key' => 'why_subtitle', 'group' => 'sections', 'value' => 'Empowering students with quality education and modern tools.sssss'],
            ['key' => 'why_reasons', 'group' => 'sections', 'value' => '[{"title":"venthan1","subtitle":"venthan2","description":"venthan13","gradient":"gradient-3","icon":"https://cdn.lordicon.com/wxnxiano.json"},{"title":"hrhrh","subtitle":"hrhrhr","description":"hrhh","gradient":"gradient-1","icon":"https://cdn.lordicon.com/qhviklyi.json"},{"title":"gerhh","subtitle":"hrhh","description":"hrhrhrh","gradient":"gradient-3","icon":"https://cdn.lordicon.com/hrjifpbq.json"}]'],
            ['key' => 'classes_types', 'group' => 'classes', 'value' => '[{"title":"Online Class","description":"Convenient live interactive sessions accessible from anywhere with high-quality digital resources.","color":"#667eea","image":"http://127.0.0.1:8000/uploads/settings/1775120678_69ce312655074.jpg","stars":"5","features":"","subjects":""},{"title":"Direct Classs  ","description":"Comprehensive face-to-face learning experience with expert tutors in a physical classroom setting.s  ","color":"#667eea","image":"http://127.0.0.1:8000/uploads/settings/1775122899_69ce39d371381.jpg","stars":"5","features":"","subjects":""}]'],
            ['key' => 'mobile_title', 'group' => 'sections', 'value' => ''],
            ['key' => 'mobile_subtitle', 'group' => 'sections', 'value' => 'EduLearn Mobile App'],
            ['key' => 'mobile_description', 'group' => 'sections', 'value' => 'Take your learning on the go with the EduLearn Mobile App, available on both iOS and Android. Access live classes, class recordings, exams, and progress updates seamlessly from your mobile device. Stay connected, stay updated, and unlock a world of learning at your fingertipsâ€”anytime, anywhere!'],
            ['key' => 'mobile_app_store_link', 'group' => 'sections', 'value' => '#'],
            ['key' => 'mobile_play_store_link', 'group' => 'sections', 'value' => 'https://play.google.com/store/apps/details?id=com.titeducation'],
            ['key' => 'mobile_card_satisfaction', 'group' => 'sections', 'value' => '99% Student Satisfactionsss'],
            ['key' => 'mobile_card_sessions', 'group' => 'sections', 'value' => '24/7 Live Sessionssss'],
            ['key' => 'mobile_screens', 'group' => 'sections', 'value' => '[]'],
            ['key' => 'mobile_features', 'group' => 'sections', 'value' => '[{"text":""}]'],
            ['key' => 'mobile_app_store_show', 'group' => 'sections', 'value' => 'off'],
            ['key' => 'mobile_play_store_show', 'group' => 'sections', 'value' => 'off'],
            ['key' => 'why_benefits', 'group' => 'sections', 'value' => '[{"text":"hdrhh"},{"text":"hsrhsh"},{"text":"gu;gog7"}]'],
            ['key' => 'onboarding_title', 'group' => 'general', 'value' => 'Onboarding Process'],
            ['key' => 'onboarding_subtitle', 'group' => 'general', 'value' => 'Follow our simple steps to join EduLearn Online Tuition ðŸ“š'],
            ['key' => 'onboarding_steps', 'group' => 'general', 'value' => '[{"id":"5","title":"hbfshshsd","description":"geaghe","icon":"https://cdn.lordicon.com/zpxybbhl.json"},{"id":"3","title":"gghg","description":"hrhshrhrhrjhrjdrj","icon":"https://cdn.lordicon.com/wjyqkiew.json"},{"id":"5","title":"rggh","description":"hrhdrhdrhrdhrh","icon":"https://cdn.lordicon.com/dxjqoygy.json"}]'],
        ];

        foreach ($settings as $s) {
            SiteSetting::updateOrCreate(['key' => $s['key']], ['group' => $s['group'], 'value' => $s['value']]);
        }
    }
}
